### PR TITLE
Make the module compatible with terraform v0.7.0

### PR DESCRIPTION
**Pull request by ainestal**
Make the module compatible with v0.7.0 by creating lists for public and private networks, instead of strings. Also create a list for AZS instead of a string.

### CODE REVIEW

**Comment by antonbabenko** [comment]
Will this PR try to recreate already created resources?

**Comment by ainestal** [comment]
@antonbabenko it didn't try to re-create anything in my tests. It was able to detect existing resources and respect them

**Comment by ainestal** [comment]
@antonbabenko : No, It doesn't recreate created resources. I've been using the modified module successfully for 3 days now with different VPCs in different environments and everything works fine.

**Comment by antonbabenko** [comment]
This is a good update. I will give it a try on my setup on Monday and merge it.

**Comment by ainestal** [comment]
@antonbabenko just 1 note, it probably the module will not be compatible with previous v0.6.16 anymore. But terraform files working with v0.7.0 are not compatible anyway (mines weren't) so I guess it not a big problem.

**Comment by antonbabenko** [comment]
I was thinking a bit about compatibility and I think if we keep `master` branch compatible with latest stable version of Terraform it should be good. For previous versions people should reference to previous tags.

**Comment by ainestal** [comment]
@antonbabenko that makes sense to me. But it should be explained in the doc. It also should be explained how to do it; when I'm importing the module I'm referencing the url of the repository without specifying any specific branch or commit. It can be confusing for people suddenly needing to specify some extra details for their module to continue working with their existing terraform (pre v0.7)

**Pull request merged**
